trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: Project
    value: AMER-West
    readonly: false
  - name: Space
    value: dev-int
    readonly: false

steps:
  - checkout: self
    persistCredentials: true
  - task: CmdLine@2
    displayName: Login to Platform
    inputs:
      script: |
        export TANZU_CLI_CEIP_OPT_IN_PROMPT_ANSWER=no
        wget https://github.com/vmware-tanzu/tanzu-cli/releases/download/v1.3.0/tanzu-cli-linux-amd64.tar.gz -O /tmp/tanzu.tar.gz
        tar -xvf /tmp/tanzu.tar.gz -C /tmp
        install /tmp/v1.3.0/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
        tanzu config eula accept
        tanzu plugin install --group vmware-tanzu/app-developer
        
        tanzu login
    env:
      TANZU_API_TOKEN: $(TanzuApiToken)

  - task: CmdLine@2
    displayName: Deploy Application
    inputs:
      script: |
        tanzu project use $PROJECT
        tanzu space use $SPACE
        
        cd amer-west/spaces/dev-int

        tanzu deploy -y