apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music-ado
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-music-ado
spec:
  contact:
    team: warroyo
  content:
    buildTimestamp: "2024-08-07T14:54:14Z"
    gitCommit: 0f2502daf6bd53af6c500505652bdc820058cb0d-dirty
    gitURL: github.com/warroyo/spring-music.git
    packageImage: ghcr.io/warroyo/spring-music-ado@sha256:1f4cb0aa7d5b69a64ce49df8dc73f5df7e74c01f012f857a053c441051a73783
    packageRefName: spring-music-ado.apps.local
    packageVersion: 20240807.1454.14188
    summary: git:0f2502d @ 2024-08-07T14:54:14Z
    version: 20240807.1454.14188
  health:
    maxUnavailableReplicas: 10%
  image: ghcr.io/warroyo/spring-music-ado@sha256:42f0c646c7669e12c5982796fbecf1c1ee5ab0f10548c4b2c48623e0e5c4bb16
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080 -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-music-ado
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-music-ado
  - for: kubernetes.service-target
    kind: Service
    name: spring-music-ado
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-music-ado-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-music-ado-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-music-ado-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-music-ado
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-music-ado.apps.local.20240807.1454.14188
  - for: kubernetes.delete
    kind: Secret
    name: spring-music-ado-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-music-ado-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: spring-music-ado-values
  resources:
    cpu: 300m
    memory: 1Gi
