apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music-ado
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: spring-music-ado
spec:
  contact:
    team: warroyo
  content:
    buildTimestamp: "2024-07-29T18:45:15Z"
    gitCommit: 395c23ccb0f623f349d00fdf9bfa0b65c9ba6c0c-dirty
    gitURL: github.com/warroyo/spring-music.git
    packageRefName: spring-music-ado.apps.local
    summary: git:395c23c @ 2024-07-29T18:45:15Z
    version: 20240729.1845.15441
  image: ghcr.io/warroyo/spring-music-ado@sha256:95fcc45cbd21773901a385bef062bb236b521a6cd9ab27b4257eda2dc01d0068
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080 -Dserver.shutdown.grace-period=24s
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=spring-music-ado
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: spring-music-ado
  - for: kubernetes.service-target
    kind: Service
    name: spring-music-ado
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: spring-music-ado-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: spring-music-ado-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: spring-music-ado-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: spring-music-ado
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: spring-music-ado.apps.local.20240729.1845.15441
  - for: kubernetes.delete
    kind: Secret
    name: spring-music-ado-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: spring-music-ado-values
  resources:
    cpu: 300m
    memory: 1Gi
