apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music-ado
  creationTimestamp: null
  name: spring-music-ado
spec:
  packageRef:
    refName: spring-music-ado.apps.local
    versionSelection:
      constraints: 20240729.1845.15441
  serviceAccountName: carvel-package-installer
  values:
  - secretRef:
      name: spring-music-ado-values
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
