apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music-ado
  creationTimestamp: null
  name: spring-music-ado.apps.local.20240730.1448.14323
spec:
  refName: spring-music-ado.apps.local
  releasedAt: "2024-07-30T14:50:10Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/spring-music-ado@sha256:7befd00567f3f90fea55d3f978c246ceb6f152b56cf6a3d1d12c0bfefa1e607d
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240730.1448.14323
